apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260521-004609-v1qvjo0qze70-service
spec:
  selector:
    app: enterprise-system-20260521-004609-v1qvjo0qze70
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
